In [1]:
from  selenium import webdriver 
from bs4 import BeautifulSoup as bs
import re 
from translate import Translator
import string
import re
from time import  sleep
from selenium.common.exceptions import TimeoutException
import pickle
from collections import deque
from selenium.webdriver.common.by import By
import pandas as pd

In [2]:
with open("state.pkl",'rb') as file:
        all_data,stack,link=pickle.load(file)
len(all_data)

4384

In [3]:
df=pd.DataFrame(all_data)

In [7]:
with open("state.pkl",'rb') as file:
        all_data2,stack2,link2=pickle.load(file)
len(all_data2)

4384

In [8]:
df=pd.DataFrame(all_data)

In [9]:
df

,price,location,data,title,link,Area (m²),Furnished,Type,Amenities,Bedrooms,Bathrooms,Level,Payment Option,Compound,Delivery Date,Delivery Term,Down Payment,Sale/Rent,vlaues
0,"5,999 EGP",Sheikh Zayed، Giza,2 March 2022,مكتب مساحة ٣١ متر بالشيخ زايد,https://www.olx.com.eg/en/ad/-IDcyvl0.html,[31],[No],"[Full, Commercial, Building]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"1,619,500 EGP",Ain Sukhna، Suez,26 February 2022,Penthouse for sale in blumar El-Sokhna,https://www.olx.com.eg/en/ad/penthouse-for-sal...,[110],[Yes],[Penthouse],"[Balcony, Central, A/C, &, heating, Security, ...",[2],[1],[2],[Cash],"[Blumar, Sokhna]","[Ready, to, move]",[Finished],NaN,NaN,NaN
2,"11,500,000 EGP",New Cairo - El Tagamoa، Cairo,27 February 2022,Good opportunity & HOT PRICE _ Villa 705 m in ...,https://www.olx.com.eg/en/ad/good-opportunity-...,[705],[No],"[Stand, Alone, Villa]","[Balcony, Private, Garden, Security, Covered, ...",[6],[6],NaN,[Cash],"[Les, Rois]","[Ready, to, move]","[Core, &, Shell]",NaN,NaN,NaN
3,"1,800,000 EGP",Rehab City، Cairo,2 March 2022,لقطططة ... للبيع بالرحاب شقة 119م بالمرحلة الع...,https://www.olx.com.eg/en/ad/119-IDcGqvm.html,[119],[No],[Apartment],NaN,[3],[3],[1],[Cash],NaN,"[Ready, to, move]",NaN,NaN,NaN,NaN
4,"5,000,000 EGP",New Capital City، Cairo,3 March 2022,لأول مرة بالعاصمة محل تجارى بعائد 495 الف وإيج...,https://www.olx.com.eg/en/ad/495-20-IDcGAWm.html,[42],NaN,[Retail],"[Covered, Parking, Security]",NaN,NaN,NaN,[Installment],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4379,"500,000 EGP",Badr City، Cairo,8 March 2022,شقة ببدر المصرية متشطبة للبيع,https://www.olx.com.eg/en/ad/-IDcHee0.html,[110],[No],[Apartment],"[Security, Electricity, Meter, Water, Meter, N...",[3],[2],[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4380,"4,000 EGP",Nakheel، Alexandria,8 March 2022,شقة مفروشة للايجار بشاطئ النخيل الاسكندريه,https://www.olx.com.eg/en/ad/-IDcHedG.html,[120],[Yes],[Apartment],[],[3],[1],[1],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4381,"490,000 EGP",Shorouk City، Cairo,8 March 2022,محل للبيع فى الشروق 16م على واجهة المول استلام...,https://www.olx.com.eg/en/ad/16-IDcHee3.html,[16],NaN,[Retail],NaN,NaN,NaN,NaN,"[Cash, or, Installment]",NaN,"[Ready, to, move]",NaN,NaN,NaN,NaN
4382,"2,800,000 EGP",Sheikh Zayed، Giza,8 March 2022,Penthouse for sale in zayed dunes 242 sqm semi...,https://www.olx.com.eg/en/ad/penthouse-for-sal...,[242],[No],[Penthouse],"[Balcony, Security, Covered, Parking, Maids, R...",[4],[4],[3],[Cash],"[Zayed, Dunes]","[Ready, to, move]","[Not, Finished]",NaN,NaN,NaN
4383,"3,000 EGP",Asyut City، Asyut,8 March 2022,شقة دور ارضي للايجار,https://www.olx.com.eg/en/ad/-IDcHedr.html,[70],[Yes],[Apartment],"[Built, in, Kitchen, Appliances, Electricity, ...",[2],[1],[Ground],NaN,NaN,NaN,NaN,NaN,NaN,NaN